AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Deliforce mobile Lambda'
Globals:
  Function:
    Environment:
      Variables:
        bucketName: lambda-constant2
        constantFileName: constant.json
      
  Deliforcemobileanalyticshourslist:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_analytics_hourslist
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_analytics_hourslist/Deliforce_mobile_analytics_hourslist.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole

  DeliforcemobileanalyticstaskComplete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_analytics_taskComplete
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_analytics_taskComplete/Deliforce_mobile_analytics_taskComplete.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole
  
  Deliforcemobiledriverstatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_driverstatus
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_driverstatus/Deliforce_mobile_driverstatus.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole  

  mobilefetchsingletask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mobile_fetch_singletask
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./mobile_fetch_singletask/mobile_fetch_singletask.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole

  Deliforcemobilegetfiles:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_getfiles
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_getfiles/Deliforce_mobile_getfiles.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole

  DeliforcemobilefileRemove:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_fileRemove
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_fileRemove/Deliforce_mobile_fileRemove.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole
  
  Deliforcemobilefileupload:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_fileupload
      Handler: lambda.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_fileupload/Deliforce_mobile_fileupload.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole
   
  Deliforcemobilenotificationget:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_notification_get
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_notification_get/Deliforce_mobile_notification_get.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole
  
  Deliforcemobileroutesget:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_routes_get
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_routes_get/Deliforce_mobile_routes_get.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole

  Deliforcemobilesettingsget:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Deliforce_mobile_settings_get
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./Deliforce_mobile_settings_get/Deliforce_mobile_settings_get.zip
      MemorySize: 3008
      Timeout: 900
      Role: arn:aws:iam::375196252534:role/deliforceRole
